sonar.projectKey=ping-watch-backend
sonar.projectName=Ping Watch Backend
sonar.projectVersion=1.0.3

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/build/**,**/.gradle/**,**/bin/**
