spring.application.name=ping-watch
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ping_watch}
spring.datasource.username=${DB_USERNAME:hoofkhanh}
spring.datasource.password=${DB_PASSWORD:hoofkhanh}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret-key=${JWT_SECRET_KEY:r5NY9xRuGCx1yfZfkGqGT8RVVW3oYncsIaB9VRvIYpU}
jwt.expiration.refresh=${JWT_REFRESH_TOKEN_EXPIRATION:180000}
jwt.expiration.access=${JWT_ACCESS_TOKEN_EXPIRATION:60000}