package com.hokhanh.ping_watch.constant;

public enum ErrorCode {
    OTP_EXPIRED,
    OTP_INVALID,
    PASSWORD_NOT_MATCH,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    USERNAME_NOT_FOUND,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_INVALID,
    USER_NOT_FOUND,
    MONITORING_CONFIGURATION_NOT_FOUND,
    INVALID_USER_ID,
    RATE_LIMIT_EXCEEDED,
}
